// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { xPayVault$Type } from "./xPayVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["xPayVault"]: xPayVault$Type;
    ["contracts/xPayVault.sol:xPayVault"]: xPayVault$Type;
  }

  interface ContractTypesMap {
    ["xPayVault"]: GetContractReturnType<xPayVault$Type["abi"]>;
    ["contracts/xPayVault.sol:xPayVault"]: GetContractReturnType<xPayVault$Type["abi"]>;
  }
}
