// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AgentNFT$Type } from "./AgentNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentNFT"]: AgentNFT$Type;
    ["contracts/AgentNFT.sol:AgentNFT"]: AgentNFT$Type;
  }

  interface ContractTypesMap {
    ["AgentNFT"]: GetContractReturnType<AgentNFT$Type["abi"]>;
    ["contracts/AgentNFT.sol:AgentNFT"]: GetContractReturnType<AgentNFT$Type["abi"]>;
  }
}
